export enum Tables {
    models = 'admin.models',
    prices = 'admin.prices',
    project_types = 'admin.project_types',
    tariffs = 'admin.tariffs',
    tariffs_controller = 'admin.tariffs_controller',
    train_controller = 'admin.train_controller',
    train_converts = 'admin.train_converts',
    train_error_logs = 'admin.train_error_logs',
    trains = 'admin.trains',
    file_metadata = 'dataset.file_metadata',
    files = 'dataset.files',
    inviteds = 'public.inviteds',
    user_meta = 'public.user_meta',
    users = 'public.users',
    classes = 'workspace.classes',
    projects = 'workspace.projects',
    roles = 'workspace.roles',
    user_drawed_images = 'workspace.user_drawed_images',
    user_projects = 'workspace.user_projects',
    user_salary = 'workspace.user_salary',
    workspaces = 'workspace.workspaces',
}
